theme: jekyll-theme-slate
title: Andy Holmes
description: Time well pasted

collections:
  articles:
    output: true
    
defaults:
  - scope:
      path: ""
      type: "articles"
    values:
      layout: "article"
      theme: "jekyll-theme-slate"
  - scope:
      path: ""
    values:
      layout: "default"
      theme: "jekyll-theme-slate"
